#logging:
#  level:
#    org.springframework.security: debug
#    org.hibernate.SQL: debug # 로거를 통한 찍는다
#    #org.hibernate.type: trace # 쿼리 파라미터 출력
server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
