name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up openjdk-1.8
        uses: actions/setup-java@v1 # 여기서는 자바 버전으로 15.0.1을 입력
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml # maven을 이용한 package 명령